env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    rclone_config: "ENCRYPTED[47d7170b64c77204002dd3daa0dc8a450b3e88423410cc70b5af65912d3a2e478d74085979973802e06c9d00c31efe32]"
    CHATID: "ENCRYPTED[1a5e8e48fa591c0d9497b92316ba7cffa3ff143bbe087f9824d894f01642f79da43f8777005d3082c205f9ac2c98d5e6]"
    API_BOT: "ENCRYPTED[025bc58bdf47cde465982e9a46a51272799e23031a8f99d7e9149238505f4eaa33c35cb5379ba11268b98a621ad83a18]"
task:
    name: notakbuzz
    timeout_in: 240m
    container:
      image: apon77/aosp:latest
      cpu: 16
      memory: 24G
    download_ccache_background_script:
      - ./download_ccache
    sync_script:
      - ./sync
    build_script:
      - ./build
    upload_ccache_script:
      - ./upload_ccache
