#!/bin/bash

MANIFEST=https://github.com/P-404/platform_manifest
BRANCH=rippa

mkdir -p /tmp/rom
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init --no-repo-verify --depth=1 -u "$MANIFEST" -b "$BRANCH" -g default,-device,-mips,-darwin,-notdefault
git config --global user.name notakbuzz
git config --global user.email bistodroid@gmail.com

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j16

# Sync stuffs
git clone https://github.com/P-404-ginkgo/ginkgo-vendor.git vendor/xiaomi/ginkgo
git clone https://github.com/P-404-ginkgo/ginkgo-dt.git device/xiaomi/ginkgo
git clone https://github.com/hpnightowl/p404_kernel_xiaomi_ginkgo.git kernel/xiaomi/ginkgo
git clone https://github.com/P-404-ginkgo/hardware_qcom_display.git hardware/qcom/display
git clone https://github.com/P-404-ginkgo/hardware_qcom_media.git hardware/qcom/media
git clone https://github.com/P-404-ginkgo/hardware_qcom_audio.git vendor/qcom/opensource/audio-hal/primary-hal
git clone https://github.com/trinket-devs/vendor_miuicamera.git vendor/miuicamera
